# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubEnvTest < Formula
  desc ""
  homepage "https://github.com/ynhummel/homebrew-tools"
  version "0.0.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ynhummel/github-env-test/releases/download/v0.0.14/github-env-test_Darwin_x86_64.tar.gz"
      sha256 "58647ea0fead6ec00c4b525784b794f272b2b38c81a3306b6e5fb8730fc963d0"

      def install
        bin.install "github-env-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ynhummel/github-env-test/releases/download/v0.0.14/github-env-test_Darwin_arm64.tar.gz"
      sha256 "d6649d6f514c0841d20c14d6d08d20def066e12d5d25fe8e2c446a102168816a"

      def install
        bin.install "github-env-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ynhummel/github-env-test/releases/download/v0.0.14/github-env-test_Linux_arm64.tar.gz"
      sha256 "743beea7c95663c6e58beb0de09bad88f56171801626ed492707e5c98732cfb3"

      def install
        bin.install "github-env-test"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ynhummel/github-env-test/releases/download/v0.0.14/github-env-test_Linux_x86_64.tar.gz"
      sha256 "9920fa0c8fad15a8fce4f56676caaf79097c10ef5a29917915dfc4393d33e264"

      def install
        bin.install "github-env-test"
      end
    end
  end
end
